### ISSUE TITLE
Declare the plugin page as safe website to Symantec Bluecoat

### ISSUE THREAD

**Issue by heurteph-ei** [openmost/TagManagerExtended#1]
Working on secured company, I can't access http://openmost.io/ as it is unknown to Symantec Bluecoat:
https://sitereview.bluecoat.com/#/lookup-result/openmost.io

Can you declare your website?
Similar request to Lukas on his own website, 1 year ago:
https://github.com/Findus23/lw1.at/issues/2

❤️

**Comment by ronan-hello** [comment]
Hi,

I know that openmost.io is still under development, will be release at the end of year 2023.

regards
